### PR TITLE
Refactor the way vertices are formed

### PR DESCRIPTION
**Pull request by dy**
So here are refactored shaders to allow for picking right/top edge values.
Related to https://github.com/plotly/plotly.js/issues/1080.

Vertex positions are now calculated in vertex shader based on rect center coordinate and weights. That allows for detecting in fragment shader which vertex is closer to the center and by that pick proper value.

The only problem I've spotted is that gl-heatmap2d test cases pick values wrongly, though _master_ branch does not pick them at all. Have to make sure that it is not the result of the PR.

### CODE REVIEW

**Comment by etpinard** [comment]
Thanks a lot @dfcreative for looking into this.

> The only problem I've spotted is that gl-heatmap2d test cases pick values wrongly

After rebasing [`heatmapgl-primetime`](https://github.com/plotly/plotly.js/compare/heatmapgl-primetime) branch onto the current plotly.js master and npm linking this `gl-heatmap2d` branch, I can confirm that this change breaks picking in the [`gl2d_heatmapgl`](https://github.com/plotly/plotly.js/compare/heatmapgl-primetime#diff-b29b9a59f13e27a91f2f8c8ba2737429) mock.

> though master branch does not pick them at all

The current master branch doesn't bundle the `heatmapgl` trace type at the moment. For reference, here's the main [index](https://github.com/plotly/plotly.js/blob/master/lib/index.js) file. So yeah, don't worry about the `master` branch.

I should add: I just `git rebase master && git push -f` the `heatmapgl-primetime` branch. I hope that helps you find the problem. Let me know if you have any questions.

**Comment by dy** [comment]
@etpinard should be fixed with e20576d772f09ba93a4f96746f8e44d9a1a661ee

**Comment by etpinard** [comment]
Nicely done :dancer:

**Review by etpinard — APPROVED** [review]

**Comment by etpinard** [comment]
@dfcreative would you mind merging and publishing these changes?

**Comment by dy** [comment]
ok

**Pull request merged**
